services:
  postgres:
    build: ./requirements/postgres
    image: postgres:custom
    container_name: postgres
    expose:
      - "5432"
    networks:
      - pong_network
    env_file:
      - .env
    secrets:
      - pgdb
      - pguser
      - pgpass
      - pg_superuser_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  auth:
    build: ./requirements/auth
    image: auth:custom
    container_name: auth
    ports:
      - "8000:8000"
    networks:
      - pong_network
    env_file:
      - .env
    secrets:
      - auth_secret_key
      - pgdb
      - pguser
      - pgpass
      - django_superuser_password
      - django_superuser_email
      - django_superuser_username
      - django_superuser_first_name
      - django_superuser_last_name
    depends_on:
      - postgres
    volumes:
    - ./site/profile_photos:/usr/src/app/media/profile_photos
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx:custom
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pong_network
    env_file:
      - .env
    depends_on:
      - auth
      - ganache
    links:
      - ganache
    volumes:
      - ./site/static:/var/www/html/static
      - ./site/media:/var/www/html/media
      - ./site/profile_photos:/var/www/html/profile_photos
      - ./site/errors:/var/www/html/errors
      - ./requirements/truffle/build/contracts:/var/www/html/contracts
    restart: always

  cron:
    build: ./requirements/cron
    image: cron:custom
    container_name: cron
    networks:
      - pong_network
    depends_on:
      - auth
    restart: always

  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - "8545:8545"
    networks:
      - pong_network
    command: ["ganache-cli", "-h", "0.0.0.0", "-p", "8545", "-i", "5777", "-l", "12000000"]
    restart: always

  truffle:
    build: ./requirements/truffle
    container_name: truffle
    depends_on:
      - ganache
    networks:
      - pong_network
    volumes:
      - ./requirements/truffle:/app
    working_dir: /app
    command: ["sh", "-c", "deploy-if-needed.sh && while :; do sleep 2073600; done"]
    restart: "no"

networks:
  pong_network:
    name: pong

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: nfs
      device: /Users/Shared/postgres/data/
      o: bind
  static_files:
    name: static_files
    driver: local
    driver_opts:
      type: none
      device: site/static
      o: bind
  media_files:
    name: media_files
    driver: local
    driver_opts:
      type: none
      device: site/media
      o: bind
  profile_photos:
    name: profile_photos
    driver: local
    driver_opts:
      type: none
      device: site/profile_photos
      o: bind
  errors:
    name: errors
    driver: local
    driver_opts:
      type: none
      device: site/errors
      o: bind


secrets:
  auth_secret_key:
    file: ./secrets/auth_secret_key.txt
  pgdb:
    file: ./secrets/pgdb.txt
  pguser:
    file: ./secrets/pguser.txt
  pgpass:
    file: ./secrets/pgpass.txt
  pg_superuser_pass:
    file: ./secrets/pgsuperuser_pass.txt
  django_superuser_password:
    file: ./secrets/django_superuser_password.txt
  django_superuser_email:
    file: ./secrets/django_superuser_email.txt
  django_superuser_username:
    file: ./secrets/django_superuser_username.txt
  django_superuser_first_name:
    file: ./secrets/django_superuser_first_name.txt
  django_superuser_last_name:
    file: ./secrets/django_superuser_last_name.txt

